version: "3"

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    environment:
      - NODE_ENV=development

  laravel-app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
